- name: clone repository of slidy-builder
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/kaosf/slidy-builder.git
    dest: /home/vagrant/repos/github.com/kaosf/slidy-builder
  register: result

- name: install slidy-builder
  become: yes
  become_user: vagrant
  shell: |
    ./configure --prefix=/home/vagrant/local
    make install
  args:
    chdir: /home/vagrant/repos/github.com/kaosf/slidy-builder
  when: result|changed
