- name: system update
  yum: name=* state=latest

- name: install some package for development
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - autoconf
    - automake
    - gcc-c++
    - ImageMagick
    - ImageMagick-devel
    - libevent
    - libevent-devel

- name: install packages
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - bind-utils
    - git
    - colordiff
    - pandoc
    - nkf
    - the_silver_searcher
    - tree
    - unzip

- name: clone repository of my dotfiles
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/mizoki/dotfiles.git
    dest: /home/{{ username }}/repos/github.com/mizoki/dotfiles

- name: check zshrc
  shell: test -f /home/{{ username }}/.zshrc
  register: result
  ignore_errors: true
  changed_when: false

- name: add symbolic link of my dotfiles
  become: yes
  become_user: "{{ username }}"
  shell: /home/{{ username }}/repos/github.com/mizoki/dotfiles/setup.sh
  when: result|failed
  args:
    chdir: /home/{{ username }}/repos/github.com/mizoki/dotfiles

- name: check setting of $PATH
  shell: cat /home/{{ username }}/.zshenv | grep -q 'export PATH=/home/{{ username }}/local/bin:$PATH'
  register: result
  ignore_errors: true
  changed_when: false

- name: set environment variable ($PATH)
  become: yes
  become_user: "{{ username }}"
  shell: echo 'export PATH=/home/{{ username }}/local/bin:$PATH' >> /home/{{ username }}/.zshenv
  when: result|failed

- name: check setting of timezone
  shell: test -f /etc/localtime && ls -l /etc/localtime | grep -q "Asia/Tokyo"
  register: result
  ignore_errors: true
  changed_when: false

- name: set timezone
  shell: ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  when: result|failed
