- name: system update
  yum: name=* state=latest

- name: install some package for development
  yum: name={{item}} state=latest
  with_items:
    - autoconf
    - automake
    - curl-devel
    - expat-devel
    - gettext
    - gettext-devel
    - gpm-libs
    - libacl-devel
    - libevent
    - libevent-devel
    - lua
    - lua-devel
    - ncurses
    - ncurses-devel
    - ncurses-libs
    - openssl-devel
    - pcre
    - pcre-devel
    - perl-ExtUtils-Embed
    - perl-core
    - perl-libs
    - python-devel
    - ruby
    - ruby-devel
    - unzip
    - zlib-devel
    - git
    - colordiff
    - nkf

- name: clone repository of luajit
  become: yes
  become_user: vagrant
  git:
    repo: http://luajit.org/git/luajit-2.0.git
    dest: /home/vagrant/local/src/luajit-2.0

- name: build luajit
  shell: make && make install
  args:
    chdir: /home/vagrant/local/src/luajit-2.0

- name: clone repository of my dotfiles
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/mizoki/dotfiles.git
    dest: /home/vagrant/repos/github.com/mizoki/dotfiles

- name: check zshrc
  shell: test -f /home/vagrant/.zshrc
  register: result
  ignore_errors: True
  changed_when: false

- name: add symbolic link of my dotfiles
  become: yes
  become_user: vagrant
  shell: /home/vagrant/repos/github.com/mizoki/dotfiles/setup.sh
  when: result|failed
  args:
    chdir: /home/vagrant/repos/github.com/mizoki/dotfiles

- name: check setting of $PATH
  shell: cat /home/vagrant/.zshenv | grep -q 'export PATH=/home/vagrant/local/bin:$PATH'
  register: result
  ignore_errors: true
  changed_when: false

- name: set environment variable ($PATH)
  become: yes
  become_user: vagrant
  shell: echo 'export PATH=/home/vagrant/local/bin:$PATH' >> /home/vagrant/.zshenv
  when: result|failed

- name: check setting of timezone
  shell: test -f /etc/localtime
  register: result
  ignore_errors: true
  changed_when: false

- name: set timezone
  shell: ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  when: result|failed
