- name: system update
  yum: name=* state=latest

- name: install some package for development
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - autoconf
    - automake
    - libevent
    - libevent-devel

- name: install packages
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - bind-utils
    - git
    - colordiff
    - pandoc
    - nkf
    - tree
    - unzip

- name: clone repository of my dotfiles
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/mizoki/dotfiles.git
    dest: /home/vagrant/repos/github.com/mizoki/dotfiles

- name: check zshrc
  shell: test -f /home/vagrant/.zshrc
  register: result
  ignore_errors: true
  changed_when: false

- name: add symbolic link of my dotfiles
  become: yes
  become_user: vagrant
  shell: /home/vagrant/repos/github.com/mizoki/dotfiles/setup.sh
  when: result|failed
  args:
    chdir: /home/vagrant/repos/github.com/mizoki/dotfiles

- name: check setting of $PATH
  shell: cat /home/vagrant/.zshenv | grep -q 'export PATH=/home/vagrant/local/bin:$PATH'
  register: result
  ignore_errors: true
  changed_when: false

- name: set environment variable ($PATH)
  become: yes
  become_user: vagrant
  shell: echo 'export PATH=/home/vagrant/local/bin:$PATH' >> /home/vagrant/.zshenv
  when: result|failed

- name: check setting of timezone
  shell: test -f /etc/localtime
  register: result
  ignore_errors: true
  changed_when: false

- name: set timezone
  shell: ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  when: result|failed
