- name: install some package for build
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - openssl-devel
    - readline-devel

- name: install package for rails
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - sqlite
    - sqlite-devel

- name: clone repository of rbenv
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/{{ username }}/.rbenv

- name: clone repository of ruby-build
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/{{ username }}/.rbenv/plugins/ruby-build

- name: check setting of rbenv
  shell: cat /home/{{ username }}/.zshenv | grep -q "rbenv init"
  register: result
  ignore_errors: true
  changed_when: false

- name: initial setting of rbenv
  become: yes
  become_user: "{{ username }}"
  shell: |
    echo '' >> /home/{{ username }}/.zshenv
    echo '# rbenv settings' >> /home/{{ username }}/.zshenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/{{ username }}/.zshenv
    echo 'eval "$(rbenv init -)"' >> /home/{{ username }}/.zshenv
    source /home/{{ username }}/.zshenv
  when: result|failed

- name: check ruby is installed
  become: yes
  become_user: "{{ username }}"
  shell: /usr/bin/zsh -l -c 'rbenv versions | grep -q "2.3.0"'
  register: result
  ignore_errors: true
  changed_when: false

- name: install ruby 2.3.0
  become: yes
  become_user: "{{ username }}"
  shell: /usr/bin/zsh -l -c 'rbenv install 2.3.0'
  when: result|failed

- name: use ruby 2.3.0
  become: yes
  become_user: "{{ username }}"
  shell: /usr/bin/zsh -l -c 'rbenv global 2.3.0'
  when: result|failed

- name: install bundler
  become: yes
  become_user: "{{ username }}"
  shell: /usr/bin/zsh -l -c 'gem install bundler'
  when: result|failed
