- name: install some package for build
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - openssl-devel
    - readline-devel

- name: install package for rails
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - sqlite
    - sqlite-devel

- name: clone repository of rbenv
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/{{ username }}/.rbenv

- name: clone repository of ruby-build
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/{{ username }}/.rbenv/plugins/ruby-build

- name: check setting of rbenv
  shell: cat /home/{{ username }}/.zshenv | grep -q "rbenv init"
  register: result
  ignore_errors: true
  changed_when: false

- name: initial setting of rbenv
  become: yes
  become_user: "{{ username }}"
  shell: |
    echo '' >> /home/{{ username }}/.zshenv
    echo '# rbenv settings' >> /home/{{ username }}/.zshenv
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/{{ username }}/.zshenv
    echo 'eval "$(rbenv init -)"' >> /home/{{ username }}/.zshenv
    source /home/{{ username }}/.zshenv
  when: result|failed

- name: check ruby is installed
  become: yes
  become_user: "{{ username }}"
  shell: export RBENV_ROOT=/home/{{ username }}/.rbenv; export PATH=$RBENV_ROOT/bin:$PATH; echo N | rbenv versions | grep -q "2.2.3"
  register: result
  ignore_errors: true
  changed_when: false

- name: install ruby 2.2.3
  become: yes
  become_user: "{{ username }}"
  shell: export RBENV_ROOT=/home/{{ username }}/.rbenv; export PATH=$RBENV_ROOT/bin:$PATH; echo N | rbenv install 2.2.3
  when: result|failed
