- name: install some package for build
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - zlib-devel
    - asciidoc
    - xmlto
    - docbook2X
    - perl-ExtUtils-MakeMaker

- name: check docbook2
  shell: test -f /usr/bin/docbook2x-texi
  register: result
  ignore_errors: true
  changed_when: false

- name: add symbolic link to docbook2x-texi
  shell: ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
  when: result|failed

- name: clone repository of git
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/git/git.git
    dest: /home/{{ username }}/repos/github.com/git/git
  register: result

- name: configure
  become: yes
  become_user: "{{ username }}"
  shell: |
    make configure
    ./configure --prefix=/home/{{ username }}/local
  args:
    chdir: /home/{{ username }}/repos/github.com/git/git
  when:
    result|changed

- name: make
  become: yes
  become_user: "{{ username }}"
  shell: make all doc info
  args:
    chdir: /home/{{ username }}/repos/github.com/git/git
  when:
    result|changed

- name: make install
  become: yes
  become_user: "{{ username }}"
  shell: make install install-doc install-html install-info && make clean
  args:
    chdir: /home/{{ username }}/repos/github.com/git/git
  when:
    result|changed

- name: check git config
  shell: cat /home/{{ username }}/.gitconfig | grep -q "\[user\]"
  register: result
  ignore_errors: true
  changed_when: false

- name: initialize setting of git
  become: yes
  become_user: "{{ username }}"
  shell: |
    git config --global user.name mizoki
    git config --global user.email h.mizoki@gmail.com
    git config --global core.editor vim
    git config --global core.excludesfile /home/{{ username }}/.gitignore
    git config --global core.pager "nkf -w | LESSCHARSET=utf-8 less"
    git config --global core.autocrlf input
  when: result|failed
