- name: Get latest peco version
  become: yes
  become_user: vagrant
  shell: curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^Location:/{print $NF}'
  register: peco_latest_version

- name: Download latest peco
  become: yes
  become_user: vagrant
  get_url:
    url: https://github.com/peco/peco/releases/download/{{ peco_latest_version.stdout }}/peco_linux_amd64.tar.gz
    dest: /tmp/peco_linux_amd64.tar.gz

- name: Extract peco
  become: yes
  become_user: vagrant
  unarchive:
    src: /tmp/peco_linux_amd64.tar.gz
    dest: /tmp/

- name: Copy to /usr/bin/
  become: yes
  become_user: vagrant
  copy:
    src: /tmp/peco_linux_amd64/peco
    dest: /home/vagrant/local/bin/
    mode: 0755
