- name: clone repository of tig
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/jonas/tig.git
    dest: /home/vagrant/repos/github.com/jonas/tig

- name: build tig
  become: yes
  become_user: vagrant
  shell: |
    make configure
    ./configure \
      --prefix=/home/vagrant/local \
      --with-ncurse
    make
    make install
    make clean
  args:
    chdir: /home/vagrant/repos/github.com/jonas/tig
