- name: clone repository of tig
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/jonas/tig.git
    dest: /home/{{ username }}/repos/github.com/jonas/tig
  register: result

- name: build tig
  become: yes
  become_user: "{{ username }}"
  shell: |
    make configure
    ./configure \
      --prefix=/home/{{ username }}/local \
      --with-ncurse
    make
    make install
    make clean
  args:
    chdir: /home/{{ username }}/repos/github.com/jonas/tig
  when: result|changed
