- name: install some package for build
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - gettext
    - gpm-libs
    - libacl-devel
    - lua
    - lua-devel
    - ncurses-devel
    - ncurses-libs
    - perl-ExtUtils-Embed
    - perl-core
    - perl-libs
    - python-devel
    - ruby
    - ruby-devel

- name: use GUI (for +clipboard)
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - gtk2-devel
    - libXt-devel

- name: clone repository of luajit
  become: yes
  become_user: "{{ username }}"
  git:
    repo: http://luajit.org/git/luajit-2.0.git
    dest: /home/{{ username }}/local/src/luajit-2.0
  register: result

- name: build luajit
  shell: make && make install
  args:
    chdir: /home/{{ username }}/local/src/luajit-2.0
  when: result|changed

- name: clone repository of vim
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/vim/vim.git
    dest: /home/{{ username }}/repos/github.com/vim/vim
  register: result

- name: build vim
  become: yes
  become_user: "{{ username }}"
  shell: |
    ./configure \
      --with-features=huge \
      --with-compiledby="mizoki <h.mizoki@gmail.com>" \
      --prefix=/home/{{ username }}/local \
      --enable-gui=gtk2 \
      --enable-fontset \
      --enable-xim \
      --enable-multibyte \
      --enable-fail-if-missing \
      --enable-luainterp=yes \
      --enable-perlinterp=yes \
      --enable-pythoninterp=yes \
      --enable-rubyinterp=yes \
      --with-x \
      --with-lua-prefix=/usr \
      --with-luajit
    make
    make install
    make distclean
  args:
    chdir: /home/{{ username }}/repos/github.com/vim/vim
  when: result|changed

- name: check loading setting of luajit
  shell: test -f /etc/ld.so.conf.d/luajit.conf
  register: result
  ignore_errors: true
  changed_when: false

- name: add loading setting of luajit
  shell: |
    echo "/usr/local/lib/" > /etc/ld.so.conf.d/luajit.conf
    ldconfig
  when: result|failed

- name: clone repository of neobundle.vim
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/Shougo/neobundle.vim.git
    dest: /home/{{ username }}/.vim/bundle/neobundle.vim
