- name: clone repository of vim
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/vim/vim.git
    dest: /home/vagrant/repos/github.com/vim/vim
  register: result

- name: build vim
  become: yes
  become_user: vagrant
  shell: |
    ./configure \
      --with-features=huge \
      --with-compiledby="mizoki <h.mizoki@gmail.com>" \
      --prefix=/home/vagrant/local \
      --with-x \
      --with-gnome \
      --enable-xim \
      --enable-fail-if-missing \
      --enable-luainterp=yes \
      --enable-perlinterp=yes \
      --enable-pythoninterp=yes \
      --enable-rubyinterp=yes \
      --with-lua-prefix=/usr \
      --with-luajit \
      --enable-multibyte
    make
    make install
    make clean
  args:
    chdir: /home/vagrant/repos/github.com/vim/vim
  when: result|changed

- name: check loading setting of luajit
  shell: test -f /etc/ld.so.conf.d/luajit.conf
  register: result
  ignore_errors: true
  changed_when: false

- name: add loading setting of luajit
  shell: |
    echo "/usr/local/lib/" > /etc/ld.so.conf.d/luajit.conf
    ldconfig
  when: result|failed

- name: clone repository of neobundle.vim
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/Shougo/neobundle.vim.git
    dest: /home/vagrant/.vim/bundle/neobundle.vim
