- name: check haskell is installed
  shell: which ghci
  register: result
  ignore_errors: true
  changed_when: false

- name: install haskell
  shell: |
    wget http://sherkin.justhub.org/el6/RPMS/x86_64/justhub-release-2.0-4.0.el6.x86_64.rpm
    rpm -ivh justhub-release-2.0-4.0.el6.x86_64.rpm
    yum install -y haskell-platform
    rm -f justhub-release-2.0-4.0.el6.x86_64.rpm
  when: result|failed

- name: check pandoc is installed
  shell: test -f /home/{{ username }}/local/bin/pandoc
  register: result
  ignore_errors: true
  changed_when: false

- name: install pandoc
  become: yes
  become_user: "{{ username }}"
  shell: |
    cabal update
    cabal install cabal-install
    ln -sf /home/{{ username }}/.cabal/bin/cabal /home/{{ username }}/local/bin/
    /home/{{ username }}/local/bin/cabal update
    /home/{{ username }}/local/bin/cabal install pandoc
    ln -sf /home/{{ username }}/.cabal/bin/pandoc /home/{{ username }}/local/bin/
  when: result|failed
