- name: clone repository of tmux
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/tmux/tmux.git
    dest: /home/{{ username }}/repos/github.com/tmux/tmux
  register: result

- name: build tmux
  become: yes
  become_user: "{{ username }}"
  shell: |
    ./autogen.sh
    ./configure --prefix=/home/{{ username }}/local
    make
    make install
    make clean
  args:
    chdir: /home/{{ username }}/repos/github.com/tmux/tmux
  when: result|changed
