- name: clone repository of tmux
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/tmux/tmux.git
    dest: /home/vagrant/repos/github.com/tmux/tmux
  register: result

- name: build tmux
  become: yes
  become_user: vagrant
  shell: |
    ./autogen.sh
    ./configure --prefix=/home/vagrant/local
    make
    make install
    make clean
  args:
    chdir: /home/vagrant/repos/github.com/tmux/tmux
  when: result|changed
