- hosts: vagrant-server
  user: vagrant
  port: 2222
  sudo: yes
  tasks:
    - name: system update
      yum: name=* state=latest

    - name: git install
      yum: name=git state=latest

    - name: zsh install
      yum: name=zsh state=latest

    - name: install some package for build of vim
      yum: name={{item}} state=latest
      with_items:
        - gettext
        - ncurses-libs
        - libacl-devel
        - gpm-libs
        - perl-core
        - perl-libs
        - perl-ExtUtils-Embed
        - python-devel
        - ruby
        - ruby-devel
        - lua
        - lua-devel
