- name: check ricty font
  shell: test -f /home/{{ username }}/.fonts/Ricty-Regular.ttf
  register: result
  ignore_errors: true
  changed_when: false

- name: install package for build
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - fontforge
    - git
    - unzip
  when: result|failed

- name: create temporary directory
  become: yes
  become_user: "{{ username }}"
  file: path=/home/{{ username }}/tmp state=directory owner={{ username }} group={{ username }} mode=0755
  when: result|failed

- name: create font directory
  become: yes
  become_user: "{{ username }}"
  file: path=/home/{{ username }}/.fonts state=directory owner={{ username }} group={{ username }} mode=0755
  when: result|failed

- name: clone repository of ricty
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/yascentur/Ricty.git
    dest: /home/{{ username }}/repos/github.com/yascentur/Ricty
  when: result|failed

- name: download Inconsolata font
  become: yes
  become_user: "{{ username }}"
  shell: |
    wget "http://levien.com/type/myfonts/Inconsolata.otf" -O "/home/{{ username }}/tmp/Inconsolata.otf"
  when: result|failed

- name: download Migu 1M font
  become: yes
  become_user: "{{ username }}"
  shell: |
    wget "http://osdn.jp/frs/redir.php?m=jaist&f=%2Fmix-mplus-ipa%2F63545%2Fmigu-1m-20150712.zip" -O "/home/{{ username }}/tmp/migu-1m-20150712.zip"
  when: result|failed

- name: unarchive Migu 1M
  become: yes
  become_user: "{{ username }}"
  unarchive:
    src: /home/{{ username }}/tmp/migu-1m-20150712.zip
    dest: /home/{{ username }}/tmp
    copy: no
  when: result|failed

- name: generate Ricty
  become: yes
  become_user: "{{ username }}"
  shell: /home/{{ username }}/repos/github.com/yascentur/Ricty/ricty_generator.sh /home/{{ username }}/tmp/Inconsolata.otf /home/{{ username }}/tmp/migu-1m-20150712/migu-1m-regular.ttf /home/{{ username }}/tmp/migu-1m-20150712/migu-1m-bold.ttf
  args:
    chdir: /home/{{ username }}/tmp
  when: result|failed

- name: install Ricty
  become: yes
  become_user: "{{ username }}"
  shell: |
    cp -f Ricty*.ttf /home/{{ username }}/.fonts/
#   fc-cache -vf
  args:
    chdir: /home/{{ username }}/tmp
  when: result|failed

- name: delete temporary directory
  become: yes
  become_user: "{{ username }}"
  file: path=/home/{{ username }}/tmp state=absent
  when: result|failed
