- name: install some package for build
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - autoconf
    - ncurses-devel
    - pcre
    - pcre-devel

- name: clone repository of zsh
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/zsh-users/zsh.git
    dest: /home/{{ username }}/repos/github.com/zsh-users/zsh
  register: result

- name: build zsh
  become: yes
  become_user: "{{ username }}"
  shell: |
    ./Util/preconfig
    ./configure --prefix=/home/{{ username }}/local --enable-pcre --enable-cap --enable-multibyte --with-tcsetpgrp
    make
    make install
    make clean
  args:
    chdir: /home/{{ username }}/repos/github.com/zsh-users/zsh
  when: result|changed

- name: change login shell to zsh
  user:
    name: "{{ username }}"
    state: present
    shell: /home/{{ username }}/local/bin/zsh
